project:
  type: website
#  output-dir: docs

website:
  title: "Peyman Kor"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: https://scholar.google.com/citations?user=di4h5_4AAAAJ&hl=en
        target: "_blank"
      - text: "Presentations"
        href: presentations
      - text: "Blog"
        href: blog/index.html
#        target: "_blank"
      - text: "CV"
        href: cv.qmd
        target: "_blank"

  twitter-card:
    creator: "@peyman_kor"
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true

collections:
  blog:
    folder: blog
    sort: date asc
    categories: true
    format:
      html:
        page-layout: full


