project:
  type: website
#  output-dir: docs

website:
  title: "Peyman Kor"
  google-analytics: G-5HXVH6767Y

  navbar:
    left:
      - text: "Peyman Kor"
        href: index.html
    right:
      - text: "Blog"
        href: blog/index.html
      - text: "Data & AI Portfolio"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Presentations"
        href: presentations
#        target: "_blank"
      - text: "Awards"
        href: awards.qmd
#      - text: "CV"
#        href: cv.qmd
#        target: "_blank"
#      - text: "Book a call"
#        href: "https://cal.com/peyman-kor-xf878d/45min"
#        target: "_blank"

  twitter-card:
    creator: "@peyman_kor"
format:
  html:
    grid:
      margin-width: 250px
      body-width: 800px
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true
    page-layout: full
    navbar-style: 
      collapse-below: lg
      background: white
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
          <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap" rel="stylesheet">

collections:
  blog:
    folder: blog
    sort: date asc
    categories: true
    format:
      html:
        page-layout: full


# So here the notes is that the. They grid control how what's a white spacing of between the front left to right. So the margin width and the margin. Another margin will control that one. But also another thing is that. Is that I can control the style CCS and the variable CCS for the detail. These two links are very nice good links for having control over the these two parameter in the quarter website. 

#https://quarto.org/docs/output-formats/html-themes.html
#https://quarto.org/docs/output-formats/page-layout.html