---
title: "Generative AI: 4 Ways It Is Transforming Human Life"
author: "Peyman Kor"
date: "2025-01-31"
categories: [genai]
---

Generative AI, as it is defined today, represents the latest form of artificial intelligence. It has emerged recently and taken the world by  storm. I would argue that the most important distinction between this wave of AI (GenAI) and previous ones is its widespread impact. This time, the technology is affecting a much larger audience. Just think about it—generative AI has reached people from all walks of life. 
My parents, who come from a third-world country, have heard of it, and it has become a part of conversations everywhere.

This technology is fundamentally built upon the collective knowledge of humanity. Generative AI has been built on the 
almost all the knowledge we human so far shared through the internet. Then, through combination of this enormous data, 
compute (100s of GPUs) and smart algorithms (transformers architecture), we human has been able to build a tool that is changing future of our world.

From a broad perspective, generative AI has undoubtedly influenced many lives. However, contrary to some fears, its purpose is not to replace humans or pose a threat. Like any technology, its goal should be to improve human lives. Think about around 100 years ago—traveling from one country to another on horses may took days, wasting time and resources. Then, airplanes revolutionized travel, making it efficient and even 
more enjoyable to travel. Similarly, before the internet, staying in touch with family required long trips, but 
now we can just reach out via video calls. I mean that technology, when used correctly, should have a net positive effect on people's lives.

## How Can Generative AI Enhance Human Life?

Given this perspective, I believe an important question is: In what ways can generative AI enhance human life? This is where I want to focus—how generative AI can improve our lives. I will structure this discussion into four key areas, each supported by some anecdotal examples from my personal life, and some examples from the news.

### 1. Automating Boring Knowledge Work

One of the primary benefits of generative AI is automating repetitive (boring!) tasks, particularly those performed by knowledge workers. Ideally, the work we do from 9 to 3 should be meaningful (at least we should strive for that). Everyone deserves, or at least need to try to find, meaningful work. Some people argue that they prefer simple, repetitive tasks without creativity, but I believe this often means they have yet to find something they truly enjoy.

For instance, I yet to see one person says that she genuinely enjoys reading data from PDFs, punching it into Excel, and submitting reports to their manager? (and do this everyday for say for 5 years) Or manually reading invoices, extracting details, and compiling summaries? These tasks are soul-crushing :) because they lack creativity and could be done by anyone. The key idea here is to identify repetitive, unfulfilling tasks in the workplace and automate them so employees can focus on more impactful work.

Consider a scenario where an employee needs to fill out standard forms for an reporting purpose to auditing company. Instead of manually completing each form, AI could generate a pre-filled template based on provided instructions, saving time and effort. I mean not 100% but the AI tool can make the draft of the form for 80%, then employee needs to do final review , double check and submit the form. This way, employees can dedicate their energy to tasks that are more impactful.

### 2. Enabling Tasks That Humans Can Not Do

Another area where generative AI can be useful is when the task is too complex or time-consuming for humans to do.  Here, human just **can not do the task.** Take, for example, a finance officer who wants to analyze 1,000 paper invoices received each month. Parsing and reading through each manually is nearly impossible, no matter how many employees are assigned to the task. However, generative AI can process the invoices, extract relevant data, and generate insightful reports, helping organizations make better decisions.

This category isn't about replacing human efforts; it's about enabling tasks that would otherwise undoable for humans.

### 3. Acting as a Personal Advisor or Coach

We all need someone to brainstorm ideas with, and generative AI can serve as an excellent brainstorming tool. Some people prefer writing their thoughts on paper, but others may struggle with that process. Generative AI provides a way to facilitate brainstorming and ideation in an interactive manner.

For example, in my personal life, I often wake up wanting to exercise. I have two workout tools at home—a pull-up bar and a extra 
chest weight. I could ask ChatGPT or (Claude, etc) to suggest a quick 30-minute workout that helps me build an athletic physique (V shape is my favorite:)). Before AI, I would have had to search for routines manually. Now, AI can instantly generate a structured plan based on my preferences.

Another example is language learning. When I receive messages in Norwegian from my friends, sometime understanding the cultural context of the message is more important than the message itself. I pass it to LLM, it can analyze the message and provide explanations, so that I can reply with better understanding. This ability to act as an advisor or coach is super valuable.

### 4. Helping Us with Better Decision-Making

Ok, now we come to the decision-making part, which has some place in my heart :). I spent much of PhD education on science of making decisions, and that field is called "Decision Science", is like an ocean. The more you know about it, the more you realize how little I know about it.

Decision-making is another area where GenAI can be a powerful tool. I found there are two ways GenAI can help people make better decisions. 

1. GenAI can help people to identify more complete list of the objectives they want to achieve  
2. Given the a better list of objectives in (1), GenAI can help people to generate more "creative" alternatives.

Lets start with the first one.

### 4.1. Helping Us to Identify More Complete List of Objectives

Fundamentally, whenever we make a decision in our life, that decision should have an objective to achieve. It's very important we make decisions to achieve the things we want, and more importantly, we need to know what we want - because how can you "proactively" think about achieving what you want without knowing what you want? This brings us to objectives and defining our values.

Research shows that when people are asked about what objectives they want to achieve, they often miss half of the things that are important to them. Let me give you an example: if you ask a young person graduating from university who is looking for an internship about what they want to get out of this internship, they may say "I want to work with a company that's 1) close to my hometown, and 2) it should have good branding that leads to a secure job." These are their two initial objectives. But if you then ask them How about learning opportunities? Do not you want to prioritize learning opportunities when evaluating the alternatives? How about having a good boss who helps you gain valuable experience?" they'll likely respond "Of course those are important, I just forgot to list them!".

Even in my personal experience, when I list the objectives I want to achieve, I often miss some important points.So here I use a ChatGPT other generative AI tools to help me out. So I write in the tools that "I'm making this particular decision and these are the objective I'm considering to evaluate my alternative. What objectives do you think I am missing?". And always, always I see some items that are, of course, important, which I had forgotten to list. My point here is that we humans are not very good at articulating the value and objective we have in our heads. So it's like something that's hidden in our brain that you need to uncover through scratching, brainstorming, or talking it through to bring those deeper level objectives and values to the surface.



### 4.2. Helping Us to Generate More "Creative" Alternatives

Another thing that I find very useful is that once you have your list of objectives - for example, when deciding to buy a house or a car - you can give these objectives to ChatGPT to help generate *creative* alternatives. Sometimes it comes up with creative new options that we can then evaluate as humans. This is particularly useful because one limitation we humans have is that we tend to generate very few alternatives on our own.

I often use this this prompt "Given these my personal values in this decision, what alternative would you suggest that would achieve my values?". There will be some back-and-forth dialogue, but overall, it's a great tool to help you achieve what you want.

## Conclusion

I believe generative AI presents an enormous opportunity. I'm optimistic about its potential because of its vast capabilities. However, like any technology, it comes with challenges. For instance, the non-deterministic nature of large language models means that even small input changes can produce vastly different outputs. Hallucinations—instances where AI generates misleading or incorrect information—are another concern. Additionally, AI-generated content can sometimes lack a human touch.

Despite these challenges, I see a bright future for generative AI. If used responsibly and if we educate people, especially younger generations, on how to use it effectively, this technology has the potential to bring significant benefits to society.



